"""
Django settings for seguimiento_tareas project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


from pathlib import Path
from datetime import timedelta

# =========================
# BASE
# =========================
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-099r5nn-=7j@q(4^r84okva#h!3+3c^y^928%nt0-5^1oit(m%'

DEBUG = False

ALLOWED_HOSTS = ['*']  # la IP de tu PC servidor

# para pruebas puedes poner:
#ALLOWED_HOSTS = ['*']



# =========================
# APPS
# =========================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',

    'tareas',
    'users.apps.UsersConfig',
]


# =========================
# MIDDLEWARE
# =========================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <- Asegurate que esté
    'django.contrib.sessions.middleware.SessionMiddleware',

    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
   
]


# =========================
# URL / WSGI
# =========================
ROOT_URLCONF = 'seguimiento_tareas.urls'

WSGI_APPLICATION = 'seguimiento_tareas.wsgi.application'


# =========================
# TEMPLATES
# =========================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# =========================
# DATABASE
# =========================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'seguimiento_tareas',
        'USER': 'seguimiento_user',
        'PASSWORD': 'seguimiento_pass',
        'HOST': 'db',
        'PORT': '3306',
    }
}


# =========================
# PASSWORD VALIDATION
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =========================
# DJANGO REST FRAMEWORK
# =========================
"""REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],

    # SOLO JWT evita conflictos de sesión / CSRF
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],

    # Por defecto, todo requiere login
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}"""


REST_FRAMEWORK = { 
'DEFAULT_RENDERER_CLASSES': [ 'rest_framework.renderers.JSONRenderer', #'rest_framework.renderers.TemplateHTMLRenderer', 
                             'rest_framework.renderers.BrowsableAPIRenderer', 
                               ], 
'DEFAULT_AUTHENTICATION_CLASSES': [ 'rest_framework.authentication.SessionAuthentication', 'rest_framework_simplejwt.authentication.JWTAuthentication', ], 
'DEFAULT_PERMISSION_CLASSES': ( 'rest_framework.permissions.AllowAny', ) }

# =========================
# SIMPLE JWT (CLAVE)
# =========================
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),

    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,

    "AUTH_HEADER_TYPES": ("Bearer",),
}


# =========================
# CORS
# =========================
"""CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

CORS_ALLOW_CREDENTIALS = True
"""

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True



# =========================
# INTERNATIONALIZATION
# =========================
"""LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
"""

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True
USE_TZ = True



# =========================
# STATIC / MEDIA
# =========================
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # <- necesario para WhiteNoise

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"  # <- opcional, solo si subís archivos



# =========================
# DEFAULT PK
# =========================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'





# =========================
# EMAIL BACKEND (CONSOLE)
# =========================
# settings.py
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'         # servidor SMTP
EMAIL_PORT = 587                      # puerto (587 para TLS)
EMAIL_USE_TLS = True                  # seguridad
EMAIL_HOST_USER = 'gonzart94@gmail.com' # tu email
EMAIL_HOST_PASSWORD = 'cvit umsu nydh rrvy' # contraseña o App Password
DEFAULT_FROM_EMAIL = 'no-reply@sistema-tareas.com'
